export const LOGO_URL = "assets/logo.svg";
export const LOGO_INVERTED_URL = "assets/logo-inverted.svg";

export const HERO_IMAGE =
  "https://lh3.googleusercontent.com/aida/AP1WRLvwAyLhY2FA3NII_yyeabmEuxwsOXtBRjvgHrCNA4EKwne0fNZcTP-28lJ7KjF1517BzF8cC0xry9GR4YdhwRyAivf-md7BGfyyuG_YNOJ6QY1ZeUTOxSEoaDtdaswHhSIsrV-tC0CTrw1t0RPZp2nfV-aSsC_r28q1oO9yCjQ7x-hFwVZudsa59Wp5THnbbAR4cc4wdiljA7WmoBNVoTmw8wExN7Jfgn8DAZF62euLHMOo6WPZCZXu8Q";

export const CATEGORIES = [
  "Calzado",
  "Camisetas",
  "Pantalones",
  "Chaquetas",
  "Accesorios",
];

function img(id) {
  return `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&q=80&w=600`;
}

function desc(name, material) {
  return `${name} de alto rendimiento con tecnología deportiva. Material ${material}, ideal para entrenamiento y competición. Diseño premium FitZone para atletas exigentes en Colombia.`;
}

/** Catálogo local (fallback) y fuente del seed Firestore — 20 productos TSP */
export const PRODUCTS = [
  {
    id: "tenis-running-elite-x",
    name: "Tenis Running Elite X",
    category: "Calzado",
    price: 489900,
    stock: 15,
    imageUrl: img("1542291026-7eec264c27ff"),
    description: desc("Tenis Running Elite X", "mesh transpirable con suela de amortiguación reactiva"),
    specs: { material: "Mesh + EVA", sizes: "38–44", color: "Negro/Naranja" },
  },
  {
    id: "camiseta-dry-fit-pro",
    name: "Camiseta Dry-Fit Pro",
    category: "Camisetas",
    price: 129900,
    stock: 2,
    imageUrl: img("1523381210434-271e8be1f52b"),
    description: desc("Camiseta Dry-Fit Pro", "100% poliéster reciclado con tecnología Dry-Fit"),
    specs: { material: "Poliéster reciclado", sizes: "S, M, L, XL", color: "Azul marino" },
  },
  {
    id: "shorts-compression-2",
    name: "Shorts Compression 2.0",
    category: "Pantalones",
    price: 95000,
    stock: 0,
    imageUrl: img("1515886657613-9f3515b0c78f"),
    description: desc("Shorts Compression 2.0", "compresión elástica de cuatro vías"),
    specs: { material: "Nylon/Spandex", sizes: "S–XL", color: "Negro" },
  },
  {
    id: "chaqueta-cortavientos-ultra",
    name: "Chaqueta Cortavientos Ultra",
    category: "Chaquetas",
    price: 289900,
    stock: 12,
    imageUrl: img("1515886657613-9f3515b0c78f"),
    description: desc("Chaqueta Cortavientos Ultra", "tejido cortaviento impermeable ligero"),
    specs: { material: "Poliéster ripstop", sizes: "S–XXL", color: "Gris oscuro" },
  },
  {
    id: "tenis-training-max",
    name: "Tenis Training Max",
    category: "Calzado",
    price: 359900,
    stock: 5,
    imageUrl: img("1542291026-7eec264c27ff"),
    description: desc("Tenis Training Max", "estabilidad lateral reforzada para cross-training"),
    specs: { material: "Sintético + caucho", sizes: "38–43", color: "Blanco" },
  },
  {
    id: "camiseta-termica-tech",
    name: "Camiseta Térmica Tech",
    category: "Camisetas",
    price: 145000,
    stock: 20,
    imageUrl: img("1523381210434-271e8be1f52b"),
    description: desc("Camiseta Térmica Tech", "tejido térmico de segunda piel"),
    specs: { material: "Poliéster térmico", sizes: "S–XL", color: "Negro" },
  },
  {
    id: "leggings-high-rise",
    name: "Leggings High-Rise",
    category: "Pantalones",
    price: 159900,
    stock: 8,
    imageUrl: img("1515886657613-9f3515b0c78f"),
    description: desc("Leggings High-Rise", "cintura alta con compresión media"),
    specs: { material: "Nylon/Spandex", sizes: "XS–L", color: "Vino tinto" },
  },
  {
    id: "gorra-performance-mesh",
    name: "Gorra Performance Mesh",
    category: "Accesorios",
    price: 79900,
    stock: 1,
    imageUrl: img("1515886657613-9f3515b0c78f"),
    description: desc("Gorra Performance Mesh", "panel mesh ventilado con ajuste trasero"),
    specs: { material: "Poliéster mesh", sizes: "Única", color: "Negro" },
  },
  {
    id: "maleta-gym-pro-40l",
    name: "Maleta Gym Pro 40L",
    category: "Accesorios",
    price: 199900,
    stock: 10,
    imageUrl: img("1515886657613-9f3515b0c78f"),
    description: desc("Maleta Gym Pro 40L", "compartimento ventilado para calzado"),
    specs: { material: "Poliéster 600D", sizes: "40L", color: "Azul FitZone" },
  },
  {
    id: "tenis-futbol-turf-pro",
    name: "Tenis Futbol Turf Pro",
    category: "Calzado",
    price: 320000,
    stock: 0,
    imageUrl: img("1542291026-7eec264c27ff"),
    description: desc("Tenis Futbol Turf Pro", "tracción multi-taco para superficies sintéticas"),
    specs: { material: "Sintético", sizes: "39–44", color: "Verde/Negro" },
  },
  {
    id: "pantalon-jogger-aero",
    name: "Pantalón Jogger Aero",
    category: "Pantalones",
    price: 175000,
    stock: 14,
    imageUrl: img("1515886657613-9f3515b0c78f"),
    description: desc("Pantalón Jogger Aero", "fit relajado con puños elásticos"),
    specs: { material: "Algodón/French Terry", sizes: "S–XXL", color: "Gris jaspe" },
  },
  {
    id: "saco-hoodie-sport",
    name: "Saco Hoodie Sport",
    category: "Chaquetas",
    price: 210000,
    stock: 3,
    imageUrl: img("1515886657613-9f3515b0c78f"),
    description: desc("Saco Hoodie Sport", "interior afelpado con capucha ajustable"),
    specs: { material: "Algodón/Poliéster", sizes: "S–XL", color: "Negro" },
  },
  {
    id: "tenis-walker-comfort",
    name: "Tenis Walker Comfort",
    category: "Calzado",
    price: 265000,
    stock: 9,
    imageUrl: img("1542291026-7eec264c27ff"),
    description: desc("Tenis Walker Comfort", "plantilla memory foam para uso diario"),
    specs: { material: "Cuero sintético", sizes: "38–44", color: "Blanco/Gris" },
  },
  {
    id: "camiseta-tanque-power",
    name: "Camiseta Tanque Power",
    category: "Camisetas",
    price: 85000,
    stock: 18,
    imageUrl: img("1523381210434-271e8be1f52b"),
    description: desc("Camiseta Tanque Power", "espalda nadadora para máxima ventilación"),
    specs: { material: "Poliéster Dry-Fit", sizes: "S–XL", color: "Naranja" },
  },
  {
    id: "shorts-basket-master",
    name: "Shorts Basket Master",
    category: "Pantalones",
    price: 115000,
    stock: 0,
    imageUrl: img("1515886657613-9f3515b0c78f"),
    description: desc("Shorts Basket Master", "longitud above-knee con bolsillos laterales"),
    specs: { material: "Poliéster mesh", sizes: "S–XXL", color: "Rojo" },
  },
  {
    id: "reloj-sport-digital",
    name: "Reloj Sport Digital",
    category: "Accesorios",
    price: 349900,
    stock: 4,
    imageUrl: img("1515886657613-9f3515b0c78f"),
    description: desc("Reloj Sport Digital", "cronómetro, pulsómetro y resistencia al agua 50m"),
    specs: { material: "Silicona + ABS", sizes: "Única", color: "Negro" },
  },
  {
    id: "tenis-trail-explorer",
    name: "Tenis Trail Explorer",
    category: "Calzado",
    price: 410000,
    stock: 11,
    imageUrl: img("1542291026-7eec264c27ff"),
    description: desc("Tenis Trail Explorer", "suela Vibram-style para terrenos irregulares"),
    specs: { material: "Mesh reforzado", sizes: "39–44", color: "Verde oliva" },
  },
  {
    id: "camiseta-polo-club",
    name: "Camiseta Polo Club",
    category: "Camisetas",
    price: 135000,
    stock: 6,
    imageUrl: img("1523381210434-271e8be1f52b"),
    description: desc("Camiseta Polo Club", "cuello polo con botones ocultos"),
    specs: { material: "Algodón/Piqué", sizes: "S–XL", color: "Blanco" },
  },
  {
    id: "chaqueta-impermeable",
    name: "Chaqueta Impermeable",
    category: "Chaquetas",
    price: 325000,
    stock: 2,
    imageUrl: img("1515886657613-9f3515b0c78f"),
    description: desc("Chaqueta Impermeable", "membrana 10K con costuras selladas"),
    specs: { material: "Nylon 10K", sizes: "S–XXL", color: "Amarillo flúor" },
  },
  {
    id: "medias-compresion-pack-3",
    name: "Medias Compresión (Pack 3)",
    category: "Accesorios",
    price: 45000,
    stock: 25,
    imageUrl: img("1515886657613-9f3515b0c78f"),
    description: desc("Medias Compresión (Pack 3)", "compresión graduada para recuperación"),
    specs: { material: "Nylon/Spandex", sizes: "36–43", color: "Negro/Gris/Blanco" },
  },
];

export function getProductById(id) {
  return PRODUCTS.find((p) => p.id === id) ?? null;
}
